

// —————————————— 
// <auto-generated> 
//	This code was auto-generated 01/27/2021 18:54:02 
//	T4 template generates viewmodel mapping profile code 
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
using System.Text;
using AutoMapper;
using TEST_MulltiTenantAPI_Demo.Entity;
namespace TEST_MulltiTenantAPI_Demo.Domain.Mapping
{
    /// <summary>
    /// 
    /// </summary>
    public partial class MappingProfile : Profile
    {
        partial void SetAddedMappingProfile()
        {
     
		}	
	} 
}

