


// —————————————— 
// <auto-generated> 
//	This code was auto-generated 01/27/2021 18:54:03
//     	T4 template generates service code
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text;
using AutoMapper;
using TEST_MulltiTenantAPI_Demo.Entity;
using TEST_MulltiTenantAPI_Demo.Entity.UnitofWork;

namespace TEST_MulltiTenantAPI_Demo.Domain.Service
{
}