


// —————————————— 
// <auto-generated> 
//	This code was auto-generated 01/27/2021 18:54:01 
//	T4 template generates viewmodel's code 
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
namespace TEST_MulltiTenantAPI_Demo.Domain
{
     
}